Repository Alfresco/third-party-license-overrides, pull requests merged in 2022-02, with the labels that each got.

#25 [AAE-7250] Add missing aliases and exceptions
  licenseMerges.txt
  override-THIRD-PARTY.properties
Labels: PR: partially-approved

#26 [AAE-7250] Add missing aliases and exceptions
  includedLicenses.txt
  licenseMerges.txt
  override-THIRD-PARTY.properties
Labels: PR: partially-approved

#27 AAE-7250 Update evidence links for a couple of dependencies.
  override-THIRD-PARTY.properties
Labels: PR: reviewed-approved

#30 [AAE-7250] Added exceptions for missing URLs and licenses - 3
  override-THIRD-PARTY.properties
Labels: PR: partially-approved

#32 ACS-2384 Keycloak licenses.
  includedLicenses.txt
  licenseMerges.txt
  override-THIRD-PARTY.properties
Labels: PR: partially-approved

#33 ACS-2072 Licenses for ACS.
  includedLicenses.txt
  licenseMerges.txt
  override-THIRD-PARTY.properties
Labels: PR: unreviewed

#34 ACS-2072 More license approvals for ACS.
  includedLicenses.txt
  licenseMerges.txt
Labels: PR: partially-approved

#35 AAE-7639 Fix all the missing licenses aliases and exceptions
  includedLicenses.txt
  licenseMerges.txt
  override-THIRD-PARTY.properties
Labels: PR: partially-approved

#36 ACS-2365 Add license for findbugs annotations.
  override-THIRD-PARTY.properties
Labels: PR: partially-approved

#37 [AAE-7639] Add LGPL-3+ override for license3j 1.0.7
  override-THIRD-PARTY.properties
Labels: PR: partially-approved

#38 [AAE-7639] Added overrides for Logback and Hibernate
  licenseMerges.txt
  override-THIRD-PARTY.properties
Labels: PR: partially-approved
